### PR TITLE
Some Fixes

### PR DESCRIPTION
**Pull request by bryanjbelanger**
Allows skipping of updates to happen using the --skip-updates flag.

Also, no longer errors out on Centos images selection.

### CODE REVIEW

**Comment by garethr** [comment]
Hi @bryanjbelanger. Sorry for the delayed response. There looks to be some useful fixes and features here but it being coupled together into one PR makes it tricky to review. Would it be possible to split this into separate PRs which address individual issues?

Alternatively, I'm happy to decompose this myself and port individual portions into our master branch if that works better for you?

**Comment by bryanjbelanger** [comment]
I’m good either way.

I don’t have a lot of time right now to split it. I guess it depends on how patient you are.

If you got time on your hands it would be the most expedient way to go.

Thanks,

Bryan

On Feb 10, 2017, at 12:29 PM, Gareth Rushgrove <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @bryanjbelanger<https://github.com/bryanjbelanger>. Sorry for the delayed response. There looks to be some useful fixes and features here but it being coupled together into one PR makes it tricky to review. Would it be possible to split this into separate PRs which address individual issues?

Alternatively, I'm happy to decompose this myself and port individual portions into our master branch if that works better for you?

**Comment by garethr** [comment]
I've merged #33 which contains the image user option, and #25 which contains the retain packages useful for git modules in r10k. I'll keep this open until I fix the allow updates issue.

Thanks again.

**Comment by garethr** [comment]
I finally got round to adding the ability to skip the installation of puppet, added in https://github.com/puppetlabs/puppetlabs-image_build/commit/8be09670fc17152c9bceca9d44d58a710736d98a. That closes off all the features from this PR. Thanks again for the suggestions, much appreciated.

**Pull request closed without merging**
